config/routes.rb
Rails.application.routes.draw do
  resources :ponumbers
  get 'welcome/index'

   root 'welcome#index'

end

app/models/ponumber.rb
class Ponumber < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ponumbers_controller.rb
class PonumbersController < ApplicationController
  def new
  end
  

  def index
    @ponumbers = Ponumber.all
  end
  
  def show
    @ponumber = Ponumber.find(params[:id])
  end
  
  def create
    @ponumber=Ponumber.new(ponumber_params)
  
    @ponumber.po = SecureRandom.hex(10)
 
ExampleMailer.sample_email(@ponumber).deliver_now

     @ponumber.save   
     redirect_to @ponumber 
  end
  

   
  private
    def ponumber_params
      params.require(:ponumber).permit(:email, :amount, :project, :po)
    end
   
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ponumbers_helper.rb
module PonumbersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Poapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/ponumbers/index.html.erb
<h1>Listing PO-Number</h1>
 
<table>
  <tr>
    <th>ID</th>
    <th>Project</th>
    <th>Amount</th>
    <th>PO</th>
    <th>Email</th>
    
  </tr>
 
  <% @ponumbers.each do |ponumber| %>
    <tr>
      <td><%= ponumber.id %></td>
      <td><%= ponumber.project %></td>
      <td><%= ponumber.amount %></td>
      <td><%= ponumber.po %></td>
      <td><%= ponumber.email %></td>
    </tr>
  <% end %>
</table>

app/views/ponumbers/new.html.erb
<h1>New PO Number</h1>
<%= form_for :ponumber, url: ponumbers_path do |f| %>
  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>
 
  <p>
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </p>
    <p>
    <%= f.label :project %><br>
    <%= f.text_field :project %>
  </p>
 
  <p>
    <%= f.submit :generate %>
  </p>
    
 
<% end %>

app/views/ponumbers/show.html.erb
<p>
<strong>Email:</strong>
  <%= @ponumber.email %>
</p>

<p>
<strong>Amount:</strong>
  <%= @ponumber.amount %>
</p>
<p>
<strong>Project:</strong>
  <%= @ponumber.project %>
</p>
<strong>PO:</strong>
  <%= @ponumber.po %>
</p>

app/views/welcome/index.html.erb
<h1>PO numbers</h1>

<%= link_to 'Ponumber', controller: 'ponumbers' %>
<br/>
<%= link_to 'New article', new_ponumber_path %>